### ISSUE TITLE
Accesses Mod Menu internals instead of using the API

### ISSUE THREAD

**Issue by Prospector** [KubeJS-Mods/KubeJS-UI#2]
https://github.com/KubeJS-Mods/KubeJS-UI/blob/0747e74a920c2a45125033bdccc9d2387d4f7a51/fabric/src/main/java/dev/latvian/kubejs/ui/fabric/FabricActions.java#L16

This here should use `ModMenuApi.createModsScreen` instead of invoking internal code directly. Also, I would recommend when you do this to update to Mod Menu > 1.15.0 which has a new package name for the API (old one still exists but is deprecated. It seems you haven't updated to a version on the new maven yet, so that is now here: https://maven.terraformersmc.com/com/terraformersmc/modmenu

Make sure to also include
```json
"breaks": {
   "modmenu": "<1.15.0"
}
```
in your fabric.mod.json so people are running an up-to-date mod menu version that has the new API.

**Comment by MaxNeedsSnacks** [comment]
Oh wow, I was actually **just** made aware of this as I went to fix the "issue" of mod menu migrating packages, I'll be sure to include this in my PR (sorry, I don't have push access to this repo yet and thus also don't get notifs for it either)

Actually, would you mind if we maybe moved the modmenu actions for KJS UI to modmenu itself, since it's basically just a JSON file and a single `Consumer<Screen>` (that you may already have elsewhere anyways)
